blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/codemate-kr/.github/discussions
    about: ì¼ë°˜ì ì¸ ì§ˆë¬¸ì´ë‚˜ í† ë¡ ì€ ì—¬ê¸°ì—ì„œ ì§„í–‰í•´ ì£¼ì„¸ìš”
  - name: ğŸŒ CodeMate ì›¹ì‚¬ì´íŠ¸
    url: https://www.codemate.kr/
    about: CodeMate ê³µì‹ ì›¹ì‚¬ì´íŠ¸ë¥¼ ë°©ë¬¸í•˜ì„¸ìš”
  - name: ğŸ“§ ì´ë©”ì¼ ë¬¸ì˜
    url: mailto:ryu_eclipse@naver.com
    about: ì§ì ‘ ë¬¸ì˜í•˜ê³  ì‹¶ìœ¼ì‹ ê°€ìš”? ì´ë©”ì¼ì„ ë³´ë‚´ì£¼ì„¸ìš”
